### ISSUE TITLE
Support field_templates (macros)

### ISSUE THREAD

**Issue by assafrabin** [tomlegkov/marine-python#17]
Exists in original marine

**Comment by tomlegkov** [comment]
## The feature:
Support aggregating multiple fields under one field. For example, when parsing a packet we don't know if it's IPv4 or IPv6 before parsing, but we know we want the source ip.

So, we'll define a new macro: `macro.ip.src: [ip.src, ipv6.src]`. And when Marine parses, it'll parse both `ip.src` and `ipv6.src` and choose the one that was parsed (under the `macro.ip.src` key). If multiple fields are parsed, choose the first one from the list.
