### ISSUE TITLE
Marine craches with SIGTRAP when init is called twice

### ISSUE THREAD

**Issue by assafrabin** [tomlegkov/marine-python#20]
```python
from marine import Marine
m = Marine('/code/marine-python/tests/fixtures/marine/libmarine.so')
m = Marine('/code/marine-python/tests/fixtures/marine/libmarine.so')
```
yields:
** (process:56844): ERROR **: 12:15:55.841: Name given to register_open_info already exists
Trace/breakpoint trap (core dumped)

**Comment by yehonatanz** [comment]
Yeah I guess we should crash with some more useful error.

**Comment by tomlegkov** [comment]
This is not as much a bug as it is a known limitation - you're not supposed to call init twice.

As for catching it - I don't think you can catch it, only maintain internal state and prevent it from being called twice (per process).
