### ISSUE TITLE
Fix StopIteration exception when no fields were extracted

### ISSUE THREAD

**Issue by yehonatanz** [tomlegkov/marine-python#41]
We incorrectly raise `StopIteration` when no fields are extracted, due to incorrect CSV parsing.
Reproduce:
```python
marine.parse_packet(b"0" * 64, fields=["ip.src"])
```
Won't be relevant if and when #35 is merged

**Comment by domerd** [comment]
@shaharyarn fixed this on this commit 1fb4df3a35ef5d9cb1be76f1766431f02669c748.
